validate-env:
    stage: validate
    rules: 
        - !reference [.base_rules, rules]
        - when: on_success
    tags: 
        - Windows
    script:
        - |
            if ($DLL_NAME -match ".*\.dll")
            {
                echo "DLL_NAME var found"
                exit 0
            }
            else 
            {
                echo "DLL_NAME var NOT found"
                exit 1
            }
