validate-version:
    stage: validate
    rules: 
        - !reference [.base_rules, rules]
        - when: on_success
    tags:
        - Windows
    script:
        - |
            if (Test-Path -Path .\version) 
            {
                $content = Get-Content .\version;
                echo $content;
                if($content -match '(\d+)\.(\d+)\.(\d+)(\.(\d+))?') 
                {
                    exit 0;
                }
                else 
                {
                    echo "Version file is invalid";
                    exit 1;
                }
            }
            else 
            {
                echo "Version file not found";
                exit 1;
            }
