stages:
  - validate
  - build
  - fix
  - test
  - deploy

include: 
  - 'jobs/*.yml'
  - 'jobs/*/*.yml'

.base_rules:
  rules:
    - if: '$CI_PROJECT_URL =~ $CI_INCLUDE_REPO'
      when: never
    - if: '$CI_COMMIT_TAG'
      when: never

variables:
  CI_INCLUDE_REPO_NAMESPACE: "scp-sl"
  CI_INCLUDE_REPO_NAME: "ci"
  CI_INCLUDE_REPO_ID: "76"
  CI_INCLUDE_REPO: "https://git.mistaken.pl/${CI_INCLUDE_REPO_NAMESPACE}/${CI_INCLUDE_REPO_NAME}"
